### ISSUE TITLE
Practica 3: Ejercicios de Inducción Matemática

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-edwin#1]
[Practica 3_Ejercicios de Inducción Matemática.pdf](https://github.com/user-attachments/files/17528896/Practica.3_Ejercicios.de.Induccion.Matematica.pdf)

**Comment by irwingsael** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:
100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..

**Comment by josealfredo79** [comment]
bien hecho y revisado..
